# # Development override for docker compose.yml
# # This file is automatically loaded by docker compose for development

# version: "3.8"

# services:
#   # Override API service for development
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile.api.dev
#     environment:
#       - NODE_ENV=development
#       - DATABASE_URL=postgresql://balda:balda@postgres:5432/balda
#       - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret}
#       - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-dev-refresh-secret}
#       - LOG_LEVEL=debug
#     volumes:
#       - .:/app
#       - /app/node_modules
#       - /app/dist
#     command: bun run dev
#     ports:
#       - "3000:3000"
#     restart: unless-stopped
#     healthcheck:
#       test:
#         [
#           "CMD",
#           "wget",
#           "--no-verbose",
#           "--tries=1",
#           "--spider",
#           "http://localhost:3000/health",
#         ]
#       interval: 30s
#       timeout: 5s
#       retries: 3
#       start_period: 10s

#   # Override web service for development
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.web.dev
#     environment:
#       - NODE_ENV=development
#     volumes:
#       - .:/app
#       - /app/node_modules
#       - /app/dist
#     command: bun run dev:web
#     ports:
#       - "5173:5173"
#     restart: unless-stopped
#     healthcheck:
#       test:
#         [
#           "CMD",
#           "wget",
#           "--no-verbose",
#           "--tries=1",
#           "--spider",
#           "http://localhost:5173",
#         ]
#       interval: 30s
#       timeout: 5s
#       retries: 3
#       start_period: 10s

#   # Override Caddy for development
#   caddy:
#     volumes:
#       - ./Caddyfile.dev:/etc/caddy/Caddyfile
#       - ./dist/web:/srv
#     restart: unless-stopped
