name: PR Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate diffs

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bun run lint

      - name: Type check
        run: bun run check

      - name: Run all tests
        run: bun test

      - name: Check coverage thresholds
        run: bun run coverage:check

      - name: Build web frontend
        run: bun run build:web

      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const coverage = fs.existsSync('./coverage/lcov.info');

            let comment = '## PR Validation Results\n\n';
            comment += '- ✅ Linting passed\n';
            comment += '- ✅ Type checking passed\n';
            comment += '- ✅ Tests passed\n';

            if (coverage) {
              comment += '- ✅ Coverage thresholds met\n';
              comment += '\nℹ️ See detailed coverage report in CI artifacts.\n';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
